const API_BASE = (() => {
  const configured = (window.APP_CONFIG?.API_BASE_URL || '').replace(/\/+$/, '');
  if (configured) return configured + '/api';
  const host = String(window.location.hostname || '').toLowerCase();
  const isLocal = host === 'localhost' || host === '127.0.0.1' || host === '[::1]';
  const isStaging = host.includes('staging');
  return isLocal ? 'http://localhost:3000/api' : (isStaging ? 'https://liga-backend-staging.onrender.com/api' : 'https://liga-backend-tt82.onrender.com/api');
})();

const CATEGORY_CONFIG = {
  tercera: {
    subtitle:'TERCERA', layoutClass:'bracket-tercera', teamSource:'tercera',
    rounds:[
      {id:'q1',slot:'slot-q1',title:'Cuartos de final',subtitle:'Cuartos de final',legs:2,helper:'Serie ida y vuelta'},
      {id:'q2',slot:'slot-q2',title:'Cuartos de final',subtitle:'Cuartos de final',legs:2,helper:'Serie ida y vuelta'},
      {id:'s1',slot:'slot-s1',title:'Semifinal',subtitle:'Semifinal',legs:2,helper:'Serie ida y vuelta'},
      {id:'final',slot:'slot-final',title:'Final',subtitle:'Final única',legs:1,helper:'Partido único'},
      {id:'third',slot:'slot-third',title:'3er y 4to puesto',subtitle:'Partido por el podio',legs:1,helper:'Partido único'},
      {id:'s2',slot:'slot-s2',title:'Semifinal',subtitle:'Semifinal',legs:2,helper:'Serie ida y vuelta'},
      {id:'q3',slot:'slot-q3',title:'Cuartos de final',subtitle:'Cuartos de final',legs:2,helper:'Serie ida y vuelta'},
      {id:'q4',slot:'slot-q4',title:'Cuartos de final',subtitle:'Cuartos de final',legs:2,helper:'Serie ida y vuelta'}
    ],
    slots:['slot-q1','slot-q2','slot-s1','slot-final','slot-third','slot-s2','slot-q3','slot-q4']
  },
  segunda: {
    subtitle:'SEGUNDA', layoutClass:'bracket-segunda', teamSource:'segunda',
    rounds:[
      {id:'s1',slot:'slot-s1',title:'Semifinal',subtitle:'Semifinal',legs:2,helper:'Serie ida y vuelta'},
      {id:'final',slot:'slot-final',title:'Final',subtitle:'Final única',legs:1,helper:'Partido único'},
      {id:'third',slot:'slot-third',title:'3er y 4to puesto',subtitle:'Partido por el podio',legs:1,helper:'Partido único'},
      {id:'s2',slot:'slot-s2',title:'Semifinal',subtitle:'Semifinal',legs:2,helper:'Serie ida y vuelta'}
    ],
    slots:['slot-s1','slot-final','slot-third','slot-s2']
  }
};

let currentCategory = 'tercera';

function normalizeTeamName(name){
  const raw = String(name || '').trim().replace(/\s+/g, ' ');
  if (!raw) return '';
  const upper = raw.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toUpperCase();
  const aliases = {'ANEXO':'ANEXO 2DA','ANEXO 2DA':'ANEXO 2DA','ANEXO 2DA.':'ANEXO 2DA','ANEXO 2DA ':'ANEXO 2DA','ANEXO 2da':'ANEXO 2DA'};
  return aliases[raw] || aliases[upper] || raw;
}
function unique(list){ return Array.from(new Set(list.filter(Boolean))); }
function getCategoryConfig(category=currentCategory){ return CATEGORY_CONFIG[category] || CATEGORY_CONFIG.tercera; }
function getEmptyLeg(){ return {date:'', home:{team:'WO',puntos:0,puntosExtra:0}, away:{team:'WO',puntos:0,puntosExtra:0}}; }
function getDefaultData(category=currentCategory){ const cfg=getCategoryConfig(category); return {rounds:cfg.rounds.map(item=>({id:item.id,title:item.title,legs:Array.from({length:item.legs},()=>getEmptyLeg())}))}; }
async function loadFromServer(category=currentCategory){ try{ const resp=await fetch(`${API_BASE}/llaves?category=${encodeURIComponent(category)}`,{cache:'no-store',credentials:'include'}); const data=await resp.json().catch(()=>null); if(!resp.ok||!data?.ok||!data?.data) throw new Error('Sin datos'); return data.data; }catch(_){ return null; } }
function getGroupsForCategory(category){ return category==='segunda'?['A','B']:['A','B','C','D']; }
function normalizeForCompare(name){ return normalizeTeamName(name).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase(); }
function parseScore(value){ const n=parseInt(value??0,10); return Number.isFinite(n)?n:0; }
async function fetchFixtureData(kind,category){ const resp=await fetch(`${API_BASE}/fixture?kind=${encodeURIComponent(kind)}&category=${encodeURIComponent(category)}`,{cache:'no-store'}); const data=await resp.json().catch(()=>null); if(!resp.ok||!data?.ok||!data?.data) throw new Error(data?.error||`No se pudo cargar fixture ${kind}`); return data.data; }
function collectFixtureEntries(ida,vuelta){ const entries=[]; [{kind:'ida',data:ida},{kind:'vuelta',data:vuelta}].forEach(feed=>{ (feed.data?.fechas||[]).forEach((fecha,idx)=>entries.push({kind:feed.kind,fechaIndex:idx+1,fecha})); }); return entries; }
function iterateGroupMatches(entries,callback){ (entries||[]).forEach(entry=>{ (entry.fecha?.tablas||[]).forEach(tabla=>{ const group=String(tabla?.grupo||'').toUpperCase(); const equipos=Array.isArray(tabla?.equipos)?tabla.equipos:[]; for(let i=0;i<equipos.length;i+=2){ const home=equipos[i], away=equipos[i+1]; if(!home||!away) continue; const homeName=normalizeTeamName(home.equipo), awayName=normalizeTeamName(away.equipo); if(!homeName||!awayName) continue; if(normalizeForCompare(homeName)==='WO'||normalizeForCompare(awayName)==='WO') continue; callback({group,home:{team:homeName,key:normalizeForCompare(homeName),puntos:parseScore(home.puntos),puntosExtra:parseScore(home.puntosExtra)},away:{team:awayName,key:normalizeForCompare(awayName),puntos:parseScore(away.puntos),puntosExtra:parseScore(away.puntosExtra)}}); } }); }); }
function computeHeadToHead(group,tiedKeys,entries){ const tied=new Set(tiedKeys); const table=Object.create(null); tiedKeys.forEach(key=>table[key]={pts:0,tr:0}); iterateGroupMatches(entries,match=>{ if(match.group!==group) return; if(!tied.has(match.home.key)||!tied.has(match.away.key)) return; table[match.home.key].pts+=match.home.puntos; table[match.home.key].tr+=match.home.puntosExtra; table[match.away.key].pts+=match.away.puntos; table[match.away.key].tr+=match.away.puntosExtra; }); return table; }
function computeStandings(category,ida,vuelta){ const groups=getGroupsForCategory(category); const entries=collectFixtureEntries(ida,vuelta); const stats=Object.fromEntries(groups.map(g=>[g,Object.create(null)])); iterateGroupMatches(entries,match=>{ if(!groups.includes(match.group)) return; [match.home,match.away].forEach(team=>{ if(!stats[match.group][team.key]) stats[match.group][team.key]={key:team.key,equipo:team.team,pts:0,tr:0,ju:0}; }); const played=match.home.puntos>0||match.away.puntos>0||match.home.puntosExtra>0||match.away.puntosExtra>0; stats[match.group][match.home.key].pts+=match.home.puntos; stats[match.group][match.home.key].tr+=match.home.puntosExtra; stats[match.group][match.away.key].pts+=match.away.puntos; stats[match.group][match.away.key].tr+=match.away.puntosExtra; if(played){ stats[match.group][match.home.key].ju+=1; stats[match.group][match.away.key].ju+=1; } }); const result={}; groups.forEach(group=>{ const rows=Object.values(stats[group]); const buckets=new Map(); rows.forEach(row=>{ const k=`${row.pts}|${row.tr}`; if(!buckets.has(k)) buckets.set(k,[]); buckets.get(k).push(row); }); const ordered=[]; Array.from(buckets.keys()).sort((a,b)=>{ const [ap,at]=a.split('|').map(Number); const [bp,bt]=b.split('|').map(Number); return (bp-ap)||(bt-at); }).forEach(k=>{ const bucket=buckets.get(k); if(bucket.length>1){ const h2h=computeHeadToHead(group,bucket.map(r=>r.key),entries); bucket.sort((a,b)=>{ const hA=h2h[a.key]||{pts:0,tr:0}, hB=h2h[b.key]||{pts:0,tr:0}; return (hB.pts-hA.pts)||(hB.tr-hA.tr)||String(a.equipo).localeCompare(String(b.equipo),'es',{sensitivity:'base'}); }); } ordered.push(...bucket); }); result[group]=ordered.map((row,idx)=>({...row,pos:idx+1})); }); return result; }
function getRound(data,id){ return data.rounds.find(round=>round.id===id); }
function setTwoLegTie(data,roundId,firstPlaceTeam,secondPlaceTeam){ const round=getRound(data,roundId); if(!round||round.legs.length<2) return; const first=normalizeTeamName(firstPlaceTeam)||'WO'; const second=normalizeTeamName(secondPlaceTeam)||'WO'; round.legs[0].home.team=second; round.legs[0].away.team=first; round.legs[1].home.team=first; round.legs[1].away.team=second; }
async function applyAutomaticEntrants(data,category){ const [ida,vuelta]=await Promise.all([fetchFixtureData('ida',category),fetchFixtureData('vuelta',category)]); const standings=computeStandings(category,ida,vuelta); const team=(group,pos)=>standings[group]?.find(row=>row.pos===pos)?.equipo||'WO'; if(category==='tercera'){ setTwoLegTie(data,'q1',team('A',1),team('B',2)); setTwoLegTie(data,'q2',team('C',1),team('D',2)); setTwoLegTie(data,'q3',team('B',1),team('A',2)); setTwoLegTie(data,'q4',team('D',1),team('C',2)); }else{ setTwoLegTie(data,'s1',team('A',1),team('B',2)); setTwoLegTie(data,'s2',team('B',1),team('A',2)); } return standings; }
function escapeHtml(value){ return String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;'); }
function formatDate(value){ if(!value) return ''; const s=String(value); const m=s.match(/^(\d{4})-(\d{2})-(\d{2})$/); return m?`${m[3]}/${m[2]}/${m[1]}`:s; }
function buildEncuentrosUrl(date){ const params=new URLSearchParams({category:currentCategory,date:String(date||'')}); return `../encuentros/encuentros.html?${params.toString()}`; }
function createLegMarkup(roundId,legIndex,legData,totalLegs){
  const isExtra=legIndex===2;
  const label=isExtra?'Desempate':(totalLegs===1?'Partido':(legIndex===0?'Ida':'Vuelta'));
  const rawDate=String(legData.date||'');
  const dateHtml=rawDate?`<a class="llaves-encuentros-btn" href="${escapeHtml(buildEncuentrosUrl(rawDate))}" aria-label="Ver encuentros del ${escapeHtml(formatDate(rawDate))}">ENCUENTROS</a>`:'';
  const rowHtml = isExtra
    ? `<div class="team-row tiebreak-team-row"><div class="score-view">${Number(legData.home.puntos||0)}</div><div class="team-view">${escapeHtml(normalizeTeamName(legData.home.team)||'WO')}</div><div class="team-view">${escapeHtml(normalizeTeamName(legData.away.team)||'WO')}</div><div class="score-view">${Number(legData.away.puntos||0)}</div></div>`
    : `<div class="team-row"><div class="score-view">${Number(legData.home.puntos||0)}</div><div class="score-view score-view-white">${Number(legData.home.puntosExtra||0)}</div><div class="team-view">${escapeHtml(normalizeTeamName(legData.home.team)||'WO')}</div><div class="team-view">${escapeHtml(normalizeTeamName(legData.away.team)||'WO')}</div><div class="score-view score-view-white">${Number(legData.away.puntosExtra||0)}</div><div class="score-view">${Number(legData.away.puntos||0)}</div></div>`;
  return `<div class="match-block ${isExtra?'match-block-extra':''}" data-round="${escapeHtml(roundId)}" data-leg="${legIndex}"><div class="match-top"><div class="match-label">${label}</div><div class="fecha-actions">${dateHtml}<div class="fecha-view">${escapeHtml(formatDate(rawDate))}</div></div></div>${rowHtml}</div>`;
}
function llGetRound(data,id){ return (data?.rounds||[]).find(r=>r.id===id); }
function llSetLegTeams(round,legIndex,homeTeam,awayTeam){ if(!round||!round.legs||!round.legs[legIndex]) return; round.legs[legIndex].home.team=normalizeTeamName(homeTeam)||'WO'; round.legs[legIndex].away.team=normalizeTeamName(awayTeam)||'WO'; }
function llIsRealTeam(name){ const n=normalizeTeamName(name); return !!n&&n!=='WO'; }
function llLegPlayed(leg){ if(!leg) return false; return [leg?.home?.puntos,leg?.away?.puntos,leg?.home?.puntosExtra,leg?.away?.puntosExtra].some(v=>Number(v||0)>0); }
function llSingleWinner(round){ const leg=round?.legs?.[0]; if(!leg||!llIsRealTeam(leg.home.team)||!llIsRealTeam(leg.away.team)||!llLegPlayed(leg)) return {winner:'WO',loser:'WO',decided:false}; const hp=Number(leg.home.puntos||0), ap=Number(leg.away.puntos||0), ht=Number(leg.home.puntosExtra||0), at=Number(leg.away.puntosExtra||0); if(hp>ap) return {winner:leg.home.team,loser:leg.away.team,decided:true}; if(ap>hp) return {winner:leg.away.team,loser:leg.home.team,decided:true}; if(ht>at) return {winner:leg.home.team,loser:leg.away.team,decided:true}; if(at>ht) return {winner:leg.away.team,loser:leg.home.team,decided:true}; return {winner:'WO',loser:'WO',decided:false}; }
function llSeriesWinner(round){ if(!round||!Array.isArray(round.legs)||round.legs.length===0) return {winner:'WO',loser:'WO',decided:false,needsExtra:false}; if(round.legs.length===1) return llSingleWinner(round); const ida=round.legs[0], vuelta=round.legs[1]; if(!ida||!vuelta||!llLegPlayed(ida)||!llLegPlayed(vuelta)) return {winner:'WO',loser:'WO',decided:false,needsExtra:false}; const firstTeam=normalizeTeamName(vuelta.home.team||ida.away.team); const secondTeam=normalizeTeamName(ida.home.team||vuelta.away.team); if(!llIsRealTeam(firstTeam)||!llIsRealTeam(secondTeam)) return {winner:'WO',loser:'WO',decided:false,needsExtra:false}; const acc={}; [firstTeam,secondTeam].forEach(t=>acc[t]={pts:0,tri:0}); [ida,vuelta].forEach(leg=>{ const h=normalizeTeamName(leg.home.team), a=normalizeTeamName(leg.away.team); if(acc[h]){ acc[h].pts+=Number(leg.home.puntos||0); acc[h].tri+=Number(leg.home.puntosExtra||0); } if(acc[a]){ acc[a].pts+=Number(leg.away.puntos||0); acc[a].tri+=Number(leg.away.puntosExtra||0); } }); const a=acc[firstTeam], b=acc[secondTeam]; if(a.pts>b.pts) return {winner:firstTeam,loser:secondTeam,decided:true,needsExtra:false}; if(b.pts>a.pts) return {winner:secondTeam,loser:firstTeam,decided:true,needsExtra:false}; if(a.tri>b.tri) return {winner:firstTeam,loser:secondTeam,decided:true,needsExtra:false}; if(b.tri>a.tri) return {winner:secondTeam,loser:firstTeam,decided:true,needsExtra:false}; const extra=round.legs[2]; if(extra&&llLegPlayed(extra)){ const hp=Number(extra.home.puntos||0), ap=Number(extra.away.puntos||0), ht=Number(extra.home.puntosExtra||0), at=Number(extra.away.puntosExtra||0); if(hp>ap) return {winner:extra.home.team,loser:extra.away.team,decided:true,needsExtra:false}; if(ap>hp) return {winner:extra.away.team,loser:extra.home.team,decided:true,needsExtra:false}; if(ht>at) return {winner:extra.home.team,loser:extra.away.team,decided:true,needsExtra:false}; if(at>ht) return {winner:extra.away.team,loser:extra.home.team,decided:true,needsExtra:false}; } return {winner:'WO',loser:'WO',decided:false,needsExtra:true}; }
function llEnsureExtraIfNeeded(data){ const target=currentCategory==='segunda'?6:5; (data.rounds||[]).forEach(round=>{ if(!['q1','q2','q3','q4','s1','s2'].includes(round.id)) return; const outcome=llSeriesWinner(round); if(outcome.needsExtra&&!round.extraDeleted){ if(round.legs.length<3){ const extra=getEmptyLeg(); extra.date=round.legs?.[1]?.date||''; extra.home.team=normalizeTeamName(round.legs?.[1]?.home?.team||round.legs?.[0]?.away?.team)||'WO'; extra.away.team=normalizeTeamName(round.legs?.[1]?.away?.team||round.legs?.[0]?.home?.team)||'WO'; round.legs.push(extra); } round.helper=`Desempate a ${target} triángulos`; } }); }
function llSetSeriesTeams(round,teamA,teamB){ if(!round||!Array.isArray(round.legs)) return; if(round.legs.length===1){ llSetLegTeams(round,0,teamA,teamB); return; } llSetLegTeams(round,0,teamB,teamA); llSetLegTeams(round,1,teamA,teamB); if(round.legs[2]) llSetLegTeams(round,2,teamA,teamB); }
function applyAutomaticAdvance(data){ llEnsureExtraIfNeeded(data); if(currentCategory==='tercera'){ const q1=llSeriesWinner(llGetRound(data,'q1')), q2=llSeriesWinner(llGetRound(data,'q2')), q3=llSeriesWinner(llGetRound(data,'q3')), q4=llSeriesWinner(llGetRound(data,'q4')); llSetSeriesTeams(llGetRound(data,'s1'),q1.winner,q2.winner); llSetSeriesTeams(llGetRound(data,'s2'),q3.winner,q4.winner); } const s1=llSeriesWinner(llGetRound(data,'s1')), s2=llSeriesWinner(llGetRound(data,'s2')); llSetSeriesTeams(llGetRound(data,'final'),s1.winner,s2.winner); llSetSeriesTeams(llGetRound(data,'third'),s1.loser,s2.loser); llEnsureExtraIfNeeded(data); return data; }
function mergeSavedEditableData(baseData,savedData){ if(!savedData||!Array.isArray(savedData.rounds)) return baseData; baseData.rounds.forEach(round=>{ const savedRound=savedData.rounds.find(r=>r?.id===round.id); if(!savedRound||!Array.isArray(savedRound.legs)) return; while(round.legs.length<savedRound.legs.length){ const savedLeg=savedRound.legs[round.legs.length]||{}; const extra=getEmptyLeg(); extra.date=typeof savedLeg.date==='string'?savedLeg.date:(round.legs?.[1]?.date||''); extra.home.team=normalizeTeamName(savedLeg?.home?.team)||normalizeTeamName(round.legs?.[1]?.home?.team)||'WO'; extra.away.team=normalizeTeamName(savedLeg?.away?.team)||normalizeTeamName(round.legs?.[1]?.away?.team)||'WO'; round.legs.push(extra); } round.extraDeleted=!!savedRound.extraDeleted; round.legs.forEach((leg,index)=>{ const savedLeg=savedRound.legs[index]; if(!savedLeg) return; leg.date=typeof savedLeg.date==='string'?savedLeg.date:leg.date; if(index>=2){ leg.home.team=normalizeTeamName(savedLeg?.home?.team)||leg.home.team; leg.away.team=normalizeTeamName(savedLeg?.away?.team)||leg.away.team; } leg.home.puntos=Number(savedLeg?.home?.puntos||0); leg.home.puntosExtra=Number(savedLeg?.home?.puntosExtra||0); leg.away.puntos=Number(savedLeg?.away?.puntos||0); leg.away.puntosExtra=Number(savedLeg?.away?.puntosExtra||0); }); }); return baseData; }
function renderBracket(mount,data,category){ const cfg=getCategoryConfig(category); mount.innerHTML=`<div class="llaves-public-box"><h2 class="llaves-public-title">Llaves eliminatorias</h2><div class="bracket-scroll"><main class="bracket ${cfg.layoutClass}" aria-label="Llaves eliminatorias"><section class="bracket-col qf-left"><div id="ll-slot-q1"></div><div id="ll-slot-q2"></div></section><section class="bracket-col sf-left"><div id="ll-slot-s1"></div></section><section class="bracket-col center-col"><div id="ll-slot-final"></div><div id="ll-slot-third"></div></section><section class="bracket-col sf-right"><div id="ll-slot-s2"></div></section><section class="bracket-col qf-right"><div id="ll-slot-q3"></div><div id="ll-slot-q4"></div></section></main></div></div>`; if(category==='segunda'){ const ql=mount.querySelector('.qf-left'), qr=mount.querySelector('.qf-right'); if(ql) ql.style.display='none'; if(qr) qr.style.display='none'; }
  cfg.rounds.forEach(config=>{ const round=data.rounds.find(r=>r.id===config.id)||{legs:[]}; const slot=mount.querySelector(`#ll-${config.slot}`); if(!slot) return; const needsExtra=['q1','q2','q3','q4','s1','s2'].includes(round.id)&&llSeriesWinner(round).needsExtra; const legsMarkup=round.legs.filter((leg,index)=>{ if(index<2) return true; if(round.extraDeleted) return false; if(needsExtra) return true; const empty=Number(leg.home?.puntos||0)===0&&Number(leg.home?.puntosExtra||0)===0&&Number(leg.away?.puntos||0)===0&&Number(leg.away?.puntosExtra||0)===0; return !empty; }).map((leg,index)=>createLegMarkup(config.id,index,leg,round.legs.length||config.legs)).join(''); slot.innerHTML=`<article class="tie-card" data-round-card="${config.id}" data-extra-deleted="${round.extraDeleted?'1':'0'}"><div class="tie-header"><div><div class="tie-subtitle">${escapeHtml(config.subtitle)}</div><h2 class="tie-title">${escapeHtml(config.title)}</h2></div></div><p class="tie-helper">${escapeHtml(config.helper)}</p><div class="round-group">${legsMarkup}</div></article>`; }); }
async function renderPublicLlaves(mount){ const category=mount.dataset.category||'tercera'; currentCategory=category; const data=getDefaultData(category); await applyAutomaticEntrants(data,category); const saved=await loadFromServer(category); mergeSavedEditableData(data,saved); applyAutomaticAdvance(data); mergeSavedEditableData(data,saved); applyAutomaticAdvance(data); renderBracket(mount,data,category); }
window.addEventListener('load',()=>{ document.querySelectorAll('#llavesPublicMount').forEach(mount=>renderPublicLlaves(mount).catch(err=>{ console.error(err); mount.innerHTML=`<div class="llaves-public-error">No se pudieron cargar las llaves</div>`; })); });
